In [ ]:
import pandas as pd # we dont need to import same library again and again if we using jupyter in one go

In [ ]:
# A series object is created with default indexing
obj1 = pd.Series([2,3,4,5])
print(obj1)

0    2
1    3
2    4
3    5
dtype: int64

In [ ]:
#creating with dictionary
obj3 = pd.Series({"hello":"world", "by":"world", "multi":"verse"})
print(obj3)

hello    world
by       world
multi    verse
dtype: object

In [ ]:
import pandas as pd
data = [[2,4], [4,53], [3,57]]
#row wise is inserted
obj4 = pd.DataFrame(data, index = ['r1', 'r2', 'r3'],columns = ['c1', 'c2'])
print(obj4, '\n')
print('using shape property obj4.shape =',obj4.shape, '\n') # its a tuple
# obj.count() or obj.count(0) or obj.count(axis = 'index')
#                obj.count(1) or obj.count(axis = 'columns')
print('obj4.count(0) will return number of non-NAN(actual values) in column of DF:')
print(obj4.count(0))

print('\nobj4.count(1) will return number of non-NAN(actual vaules) in rows of DF:')
print(obj4.count(1))

print('\nAccessing single element obj4.c2[2]')
print(obj4.c2[2]) # zero based
# or print(obj4.c2['r3'])

#? print(obj4.c2)

    c1  c2
r1   2   4
r2   4  53
r3   3  57

using shape property obj4.shape = (3, 2)

obj4.count(0) will return number of non-NAN(actual values) in column of DF:
c1    3
c2    3
dtype: int64

obj4.count(1) will return number of non-NAN(actual vaules) in rows of DF:
r1    2
r2    2
r3    2
dtype: int64

Accessing single element obj4.c2[2]
57

In [ ]:
print(obj4)
print('\n')

# obj[ [ <col1>, <col2>, <col3>, <col4>,... ] ]

# obj.col1

# using loc will include starting and ending index
# obj4.loc[ <startrow> : <endrow>, <startcol> : <endcol> ]
print(obj4.loc['r1':'r2' ,'c1':'c2'])
print('\n')
# changing value
obj4['c3'] = 1234
# what will happen? obj4['r4'] = 567
print(obj4, '\n')
# obj4[1][1] = 34 will not work
obj4['c4'] = [6,7,8]
print(obj4, '\n')

# Row updation and addition
# obj4.loc[<row name>, : ] = [] # list size has to be same as number of columns
# obj4.loc[<row name>, : ] = scalarValue # same value given to all col of the give row

# Coloumn updation and addition
# obj4['c5'] = [] # list size has to be same as number of row in the DF

# Single value updation
# obj.col['row'] = newValue

    c1  c2    c3  c4
r1   2   4  1234   6
r2   4  53  1234   7
r3   3  57  1234   8


    c1  c2
r1   2   4
r2   4  53


    c1  c2    c3  c4
r1   2   4  1234   6
r2   4  53  1234   7
r3   3  57  1234   8

    c1  c2    c3  c4
r1   2   4  1234   6
r2   4  53  1234   7
r3   3  57  1234   8

In [ ]:
# obj4.groupby('col')
# all the other coloumns are mapped to the uniques values of col elements
print(obj4, '\n\n', 'Grouping\n')

for x, y in obj4.groupby('c3'):
    print(x)
    print(y)
    print()

#renaming rows and columns
# <DF>.rename(index = {<names dictionary>}, columns = {<names dictionary>}, inplace = False)
print("Changing inplace")
print(obj4.rename(index = {'r1':'R1', 'r2':'R2', 'r3':'R3'}, columns = {'c1':'C1', 'c2':'C2', 'c3':'C4', 'r4':'R4', 'c4': 'C5'}, inplace = False))
print("\nNo in place change")
print(obj4)

    c1  c2    c3  c4
r1   2   4  1234   6
r2   4  53  1234   7
r3   3  57  1234   8

 Grouping

1234
    c1  c2    c3  c4
r1   2   4  1234   6
r2   4  53  1234   7
r3   3  57  1234   8

Changing inplace
    C1  C2    C4  C5
R1   2   4  1234   6
R2   4  53  1234   7
R3   3  57  1234   8

No in place change
    c1  c2    c3  c4
r1   2   4  1234   6
r2   4  53  1234   7
r3   3  57  1234   8

In [ ]:
import pandas as pd
r1 = [1,2,3]
r2 = [4,5,6]
r3 = [7,8,9]
r4 = [1000, 2000]
r5 = [4000, 5000]
r6 = [7000, 8000]
df1 = pd.DataFrame(data = [r1, r2, r3], columns = ['A', 'B', 'C'])
df2 = pd.DataFrame(data = [[10,20,30], [40,50,60], [70,80,90]], columns = ['A', 'B', 'C'])
df3 = pd.DataFrame(data = {'A': [100, 400], 'B':[200, 500], 'C':[300, 600]})
df4 = pd.DataFrame(data = [r4, r5, r6], index = [0,1,2], columns = ['A', 'B'])
print(df1)
print()
print(df2)
print()
print(df3)
print()
print(df4)
print()
print("Adding two data frames")
print(df1 + df2)# df = df1 + df3 or df = df1.add(df2)
print()
print("Subtracting two data frames")
print(df3 - df4)# df = df3 - df4 or df = df3.sub(df4)
print()
print("multiplying two data frames")# df = df3*df2 or df = df3.mul(df2)
print(df3*df2)
print()
print("Dividing two data frames")# df = df1 / df4 or df = df1.div(df4)
print(df1 / df4)
print()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90

     A    B    C
0  100  200  300
1  400  500  600

      A     B
0  1000  2000
1  4000  5000
2  7000  8000

Adding two data frames
    A   B   C
0  11  22  33
1  44  55  66
2  77  88  99

Subtracting two data frames
        A       B   C
0  -900.0 -1800.0 NaN
1 -3600.0 -4500.0 NaN
2     NaN     NaN NaN

multiplying two data frames
         A        B        C
0   1000.0   4000.0   9000.0
1  16000.0  25000.0  36000.0
2      NaN      NaN      NaN

Dividing two data frames
       A      B   C
0  0.001  0.001 NaN
1  0.001  0.001 NaN
2  0.001  0.001 NaN

In [ ]:
# axis = 0, along the row for each column (default behaviour)
# axis = 1, along the col for each row
print(df1)
print("getting the minimum for each column")
print(df1.min())# axis = 0, minimum for each column
print()
print("getting the minimum for each row")
print(df1.min(axis = 1))
print()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
getting the minimum for each column
A    1
B    2
C    3
dtype: int64

getting the minimum for each row
0    1
1    4
2    7
dtype: int64

In [ ]:
# Changing type of a column using .astype(newType)
# students['grade'] = students['grade'].astype(int)
# products['quantity'] = products['quantity'].fillna(0)
# DF = pd.concat([df1, df2])// should have same number of coloumns
data = [['tom', 10, 89], ['nick', 15, 86], ['juli', 14, 99]]
df = pd.DataFrame(data, columns=['Name', 'Age', 'marks'])
print(df)
print()
print(df.sum()) # axis = 0, 1 # skipna
print()
print(df.count()) # axis = 0, 1 #skipna
print()
print(df.mean()) # axis = 0, 1 #skipna
# print(df.mode()) # axis = 0, 1 #skipna
# print(df.median()) # axis = 0,1 #skipna

print()
print()
data = {
    'City': ['Jacksonville', 'Jacksonville', 'Jacksonville', 'Jacksonville', 'Jacksonville',
             'ElPaso', 'ElPaso', 'ElPaso', 'ElPaso', 'ElPaso'],
    'Month': ['January', 'February', 'March', 'April', 'May'] * 2,
    'Temperature': [13, 23, 38, 5, 34, None, 6, 26, 2, 43],
    'Randoms':[32,5,34,54,6,6,64,6,3,6],
}

dft = pd.DataFrame(data)

print(dft)
print()
dft.pivot(index = 'City', columns = 'Month', values = 'Temperature')
# dft.melt()

   Name  Age  marks
0   tom   10     89
1  nick   15     86
2  juli   14     99

Name     tomnickjuli
Age               39
marks            274
dtype: object

Name     3
Age      3
marks    3
dtype: int64

Age      13.000000
marks    91.333333
dtype: float64


           City     Month  Temperature  Randoms
0  Jacksonville   January         13.0       32
1  Jacksonville  February         23.0        5
2  Jacksonville     March         38.0       34
3  Jacksonville     April          5.0       54
4  Jacksonville       May         34.0        6
5        ElPaso   January          NaN        6
6        ElPaso  February          6.0       64
7        ElPaso     March         26.0        6
8        ElPaso     April          2.0        3
9        ElPaso       May         43.0        6

<ipython-input-16-1a17f4713513>:13: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(df.mean()) # axis = 0, 1 #skipna

Month         April  February  January  March   May
City
ElPaso          2.0       6.0      NaN   26.0  43.0
Jacksonville    5.0      23.0     13.0   38.0  34.0

In [ ]:
dft.isnull().sum()

City           0
Month          0
Temperature    1
Randoms        0
dtype: int64

In [ ]:
dft.describe()

       Temperature    Randoms
count     9.000000  10.000000
mean     21.111111  21.600000
std      15.317020  22.862876
min       2.000000   3.000000
25%       6.000000   6.000000
50%      23.000000   6.000000
75%      34.000000  33.500000
max      43.000000  64.000000